version: '3'
services:
  ofs-server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    env_file: ./server/.env
    ports:
      - 3030:3030
    volumes:
      - ./server:/app/server

  ofs-client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./client:/app/client
